name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: Run ESLint and Prettier Check
        run: pnpm lint

  svelte_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: Run Svelte Check
        run: pnpm check

  playwright_tests:
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myfit
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/myfit" >> $GITHUB_ENV

      - name: Initialize database schema
        run: pnpm exec prisma db push

      - name: Generate AUTH_SECRET
        run: echo "AUTH_SECRET=$(openssl rand -base64 33)" >> $GITHUB_ENV

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
